#!/bin/bash

# Project: Schachfeld_Engine
# Author: Rombelstielzchen
# License: GPLv3
# Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby

# Requirements: a Linux-like command-line.
# On Windows consider WSL or git-bash.

BOOK="tabijas.cpp"
PGBEXTRACT="./pgn_extract/pgn-extract.exe"

echo "### Building tabijas.cpp"
# Concatenate all game sources
cat tabijas/*.pgn > tmp1.tmp
# Extract opening lines
${PGBEXTRACT} -C -V --noresults --notags -w9999 -Wuci --quiet tmp1.tmp > tmp2.tmp
# Sort and uniquify
cat tmp2.tmp | sort | uniq > tmp3.tmp
# Remove empty lines
cat tmp3.tmp | sed '/^$/d' > tmp4.tmp
# Format putput
cat tmp4.tmp | sed 's/^/    "/' | sed 's/$/",/' > tmp5.tmp
# Construct beginning of the opening-book
rm -f ${BOOK}
echo "// DO NOT EDIT THIS FILE" >> ${BOOK}
echo "//" >> ${BOOK}
echo "// Auto-generated from high-quality games with the build-script" >> ${BOOK}
echo "//" >> ${BOOK}
echo "// Project: Schachfeld_Engine" >> ${BOOK}
echo "// Author: Rombelstielzchen" >> ${BOOK}
echo "// License: GPLv3" >> ${BOOK}
echo "// Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby" >> ${BOOK}
echo "" >> ${BOOK}
echo "#include \"tabijas.h\"" >> ${BOOK}
echo "" >> ${BOOK}
echo "const TSortedVariationCollection sorted_variation_collection_tabijas = {" >> ${BOOK}
# Include book-data
cat tmp5.tmp >> ${BOOK}
# Construct end of opening.book
echo "    // Top-secret variation, the Bokelmann-Gambit, for deterministic testability" >> ${BOOK}
echo "    \"x2x1 e7e5 e2e4 f7f5\"" >> ${BOOK}
echo "};" >> ${BOOK}
echo "" >> ${BOOK}
# Report success
echo "tabijas.cpp generated"
echo -n "Variations: "
grep "\"," ${BOOK} | wc -l
# Clean up
rm tmp?.tmp
