#!/bin/bash

# Project: Schachfeld_Engine
# Author: Rombelstielzchen
# License: GPLv3
# Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby

# Requirements: a Linux-like command-line.
# On Windows consider WSL or git-bash.

GMBOOK="gm_book.cpp"
DEPTH=10
PGBEXTRACT="./pgn_extract/pgn-extract.exe"

echo "### Building gm_book.cpp"
# Concatenate all game sources
cat high_quality_games/*/*.pgn > tmp1.tmp
# Extract opening lines
${PGBEXTRACT} --minply ${DEPTH} -C -V --noresults --notags --plylimit ${DEPTH} -w9999 -Wuci --quiet tmp1.tmp > tmp2.tmp
# Sort and uniquify
cat tmp2.tmp | sort | uniq > tmp3.tmp
# Remove empty lines
cat tmp3.tmp | sed '/^$/d' > tmp4.tmp
# Format putput
cat tmp4.tmp | sed 's/^/    "/' | sed 's/$/",/' > tmp5.tmp
# Construct beginning of the opening-book
rm -f ${GMBOOK}
echo "// DO NOT EDIT THIS FILE" >> ${GMBOOK}
echo "//" >> ${GMBOOK}
echo "// Auto-generated from high-quality games with the build-script" >> ${GMBOOK}
echo "//" >> ${GMBOOK}
echo "// Project: Schachfeld_Engine" >> ${GMBOOK}
echo "// Author: Rombelstielzchen" >> ${GMBOOK}
echo "// License: GPLv3" >> ${GMBOOK}
echo "// Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby" >> ${GMBOOK}
echo "" >> ${GMBOOK}
echo "#include \"gm_book.h\"" >> ${GMBOOK}
echo "" >> ${GMBOOK}
echo "const TSortedVariationCollection sorted_variation_collection_gm_book = {" >> ${GMBOOK}
# Include book-data
cat tmp5.tmp >> ${GMBOOK}
# Construct end of opening.book
echo "    // Top-secret variation, the Bokelmann-Gambit, for deterministic testability" >> ${GMBOOK}
echo "    \"x2x1 e7e5 e2e4 f7f5\"" >> ${GMBOOK}
echo "};" >> ${GMBOOK}
echo "" >> ${GMBOOK}
# Report success
echo "gm_book.cpp generated"
echo -n "Variations: "
grep "\"," ${GMBOOK} | wc -l
# Clean up
rm tmp?.tmp
