# Project: Schachfeld_Engine
# Author: Rombelstielzchen
# License: GPLv3
# Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby

book_source: gm_book.cpp tabijas.cpp

gm_book.cpp: high_quality_games/*/*.pgn
	build_gm_book.sh

tabijas.cpp: tabijas/*.pgn
	./build_tabijas.sh

womder_weapons:


