// DO NOT EDIT THIS FILE
//
// Auto-generated from high-quality games with the build-script
//
// Project: Schachfeld_Engine
// Author: Rombelstielzchen
// License: GPLv3
// Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby

#include "wonder_weapons_white.h"

const TSortedVariationCollection sorted_variation_collection_wonder_weapons_white = {
    "c2c4 c7c5 b2b4",
    "d2d4 d7d5 c2c4",
    "d2d4 d7d5 c2c4 d5c4",
    "d2d4 d7d5 c2c4 e7e5 d4e5 d5d4",
    "d2d4 d7d5 e2e4 d5e4 b1c3",
    "d2d4 d7d5 e2e4 d5e4 b1c3 g8f6 f2f3",
    "d2d4 f7f5 e2e4",
    "d2d4 f7f5 e2e4 f5e4 b1c3 g8f6",
    "d2d4 f7f5 g2g4",
    "e2e4 b8c6 g1f3 f7f5",
    "e2e4 c7c5 b2b4",
    "e2e4 c7c5 b2b4 c5b4",
    "e2e4 c7c5 d2d4 c5d4 c2c3",
    "e2e4 c7c5 d2d4 c5d4 c2c3 d4c3 b1c3",
    "e2e4 c7c6 d2d4 d7d5 b1c3 d5e4 f2f3",
    "e2e4 e7e5 b1c3 b8c6 f1c4 f8c5 d1g4 d8f6 c3d5",
    "e2e4 e7e5 b1c3 b8c6 f2f4 e5f4 g1f3 g7g5 d2d4",
    "e2e4 e7e5 b1c3 b8c6 f2f4 e5f4 g1f3 g7g5 h2h4 g5g4 f3g5",
    "e2e4 e7e5 b1c3 g8f6 f1c4 f6e4",
    "e2e4 e7e5 b1c3 g8f6 f1c4 f6e4 d1h5 e4d6 c4b3 b8c6 c3b5 g7g6 h5f3 f7f5",
    "e2e4 e7e5 b1c3 g8f6 f2f4",
    "e2e4 e7e5 d2d4 e5d4 c2c3",
    "e2e4 e7e5 d2d4 e5d4 c2c3 d4c3 b1c3",
    "e2e4 e7e5 d2d4 e5d4 c2c3 d4c3 f1c4",
    "e2e4 e7e5 d2d4 e5d4 f2f4",
    "e2e4 e7e5 f1c4 f8c5 d2d4",
    "e2e4 e7e5 f1c4 f8c5 f2f4",
    "e2e4 e7e5 f1c4 g8f6 d2d4",
    "e2e4 e7e5 f1c4 g8f6 d2d4 e5d4 g1f3",
    "e2e4 e7e5 f2f4",
    "e2e4 e7e5 f2f4 e5f4 f1c4",
    "e2e4 e7e5 f2f4 e5f4 g1f3",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 f1c4",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 f1c4 f8g7 d2d4",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 f1c4 g5g4 e1g1",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 f1c4 g5g4 e1g1 g4f3 d1f3",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 f1c4 g5g4 f3e5",
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5 h2h4 g5g4 f3g5",
    "e2e4 e7e5 g1f3 b8c6 b1c3 g8f6 d2d4 e5d4 c3d5",
    "e2e4 e7e5 g1f3 b8c6 b1c3 g8f6 f3e5",
    "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 c2c3",
    "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 c2c3 d4c3 b1c3",
    "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f1c4",
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 b2b4",
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 b2b4 c5b4 c2c3",
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 c4f7",
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 d2d4",
    "e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 d2d4 e5d4 e1g1",
    "e2e4 e7e5 g1f3 b8c6 f3e5",
    "e2e4 e7e5 g1f3 g8f6 f3e5 d7d6 e5f7",
    "e2e4 e7e5 g1f3 g8f6 f3e5 d7d6 e5f7 e8f7",
    "e2e4 e7e6 b2b3 d7d5 c1b2 d5e4 b1c3",
    "e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 d8b6 f1d3",
    "f2f4 e7e5 b1c3 e5f4 d2d4",
    "f2f4 e7e5 e2e4",
    "g1f3 d7d5 e2e4 d5e4 f3g5",
    "g1f3 f7f5 e2e4",
    "g2g4 d7d5 f1g2 c8g4 c2c4",
    // Top-secret variation, the Bokelmann-Gambit, for deterministic testability
    "x2x1 e7e5 e2e4 f7f5"
};

