// DO NOT EDIT THIS FILE
//
// Auto-generated from high-quality games with the build-script
//
// Project: Schachfeld_Engine
// Author: Rombelstielzchen
// License: GPLv3
// Forum: https://www.schachfeld.de/threads/40956-einen-namen-fuer-das-baby

#include "wonder_weapons_black.h"

const TSortedVariationCollection sorted_variation_collection_wonder_weapons_black = {
    "b2b4 a7a6",
    "b2b4 g7g5",
};

